version: '3.4'

services:
  staj:
    image: ${DOCKER_REGISTRY-}staj
    build:
    
      context: .
      dockerfile: Staj/Dockerfile
    ports:
       - "8000:80"
    depends_on:
    - db
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
            SA_PASSWORD: "Passw0rd"
            ACCEPT_EULA: "Y"